version: '3.8'

services:
  db:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/strongpassword123
    volumes:
      - neo4j_data:/data

  app:
    build: .
    ports:
    - "127.0.0.1:3000:3000"
    depends_on:
      - db

volumes:
  neo4j_data:
