version: '3.8'

services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/strongpassword123
    volumes:
      - neo4j_data:/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
